### ISSUE TITLE
Packet IN via Http request

### ISSUE THREAD

**Issue by adibrastegarnia** [ciena/oftee#2]
Hi, 

I would like to know oftee sends the whole OFmessage or just its data part? 

Thanks,
Adib

**Comment by adibrastegarnia** [comment]
I am getting only data part not OF headers.

**Comment by dbainbri-ciena** [comment]
`TeeRawPackets` defaults to `true` and when this is true only the packets are sents, not the OF headers. perhaps this should default to `false`

**Comment by dbainbri-ciena** [comment]
And actually, there is a context sent in front of the OF packet. It is a context and consists of the DPID and port for the Packet In message. The DPID is 64 bits and the port is 32bits

**Comment by dbainbri-ciena** [comment]
just committed a change to the default. so now, by default, the context + of header + packet is sent/
