### ISSUE TITLE
inject.Stop undefined 

### ISSUE THREAD

**Issue by adibrastegarnia** [ciena/oftee#3]
It looks like the injector does not have stop method. The code cannot be executed.

**Comment by dbainbri-ciena** [comment]
I was running it many time today. Let me do a clean pull and try ...

**Comment by dbainbri-ciena** [comment]
Just did a fresh

```
git clone http://github.com/ciena/oftee
cd oftee
docker build --rm -t oftee:test .
```

and it all worked.

**Comment by adibrastegarnia** [comment]
When I run 
go run oftee.go

I get: 
 command-line-arguments
./oftee.go:158:14: inject.Stop undefined (type *injector.Injector has no field or method Stop)

**Comment by dbainbri-ciena** [comment]
I am not sure of your environment, you may not have updated source, or your GOPATH might be pulling from the wrong area. The `Stop` method is defined in `src/github.com/ciena/oftee/injector/injector.go`. If there is not a Stop `func` in that file, your source may be wrong.

The following should work (go expects a "workspace" for development)

```
mkdir my-ws
cd my-ws
export GOPATH=$(pwd)
go get github.com/ciena/oftee
go run src/github.com/ciena/oftee/oftee.go
```

You can always run oftee as a Docker container as well

```
docker run -ti --rm --name oftee ciena/oftee
```

**Comment by adibrastegarnia** [comment]
It is working now. Previously, I just pulled and ran again and I don't what
happened.

Thanks,
Adib

**Comment by dbainbri-ciena** [comment]
Glad to hear it.
