### ISSUE TITLE
LLDP packets

### ISSUE THREAD

**Issue by adibrastegarnia** [ciena/oftee#4]
Hi,

I found out I get LLDP packets even when I set Ethernet type to : dl_type=0x800
In addition, the value of ethType is a  negative number (-30398) when I print it (i.e. this happens for LLDP packet):
 

Is this behavior normal?

Thanks

**Comment by dbainbri-ciena** [comment]
reference: https://en.wikipedia.org/wiki/EtherType

`0x0800` is v4 IP, so matches quite a lot of packets. `LLDP` is meant to be `0x88cc`, so I am not sure why you are seeing LLDP. What OFTEE configuration are you using for the TEE_TO parameter?

**Comment by adibrastegarnia** [comment]
Sometimes I get LLDP packets even when the configuration is set to send just IP packets: 
dl_type=0x800;action=http://127.0.0.1:8000/packet

Let me check one more time and then let you know. 

Thanks,
Adib

**Comment by dbainbri-ciena** [comment]
I would check the flows on the switch. ONOS [verified] and ODL [I suspect] push a flow rule for LLDP `0x88cc` to "packet in" to the controller. They use LLDP to track topology information. 

If this is the case, OFTEE will see the packet in, but it should not be forwarded to your application. Are you seeing the packet in your application or just in the OFTEE logs?

**Comment by adibrastegarnia** [comment]
I am getting the LLDP packet in my application. I print the Ethernet type of the received packet but it is not LLDP (eth type is a negative number: -30398) but my java application detects it as an LLDP packet when I want to get its payload: 
java.lang.ClassCastException: org.onlab.packet.LLDP cannot be cast to org.onlab.packet.IPv4

It can be handled by using an if condition but I am wondering why I am getting LLDP packets. 
I use onos for testing purposes. 

In addition, it happens sometimes not all the times. 

Thanks,
Adib

**Comment by dbainbri-ciena** [comment]
When you print out the ethertype are you printing it as an Integer or Unsigned integer. The ethertype is 16 bit unsigned value. In Java, I would print it something like
```
short sVal = -30398; // The original unsigned short value (16 bits), Java has not unsigned types
int iVal = sVal & 0xffff; // Convert it to an int (next largest bit number to make is "unsigned"
System.out.printf("%x\n", iVal); // print it as a hex value
```

In your example, the value turns out to be `0x8942`.

**Comment by dbainbri-ciena** [comment]
The packet you get to your application, assuming you are not using RAW packets from OFTEE, should be prefixed by the DPID and port number, followed by the complete OpenFlow PacketIn message.

You should only be getting, in your application, the packets that match the specified ethertypes. If you are getting packets that you haven't selected then it could be a bug and I would like to find it. Can you post the oftee DEBUG logs when you are getting a packet you didn't select?

There should be a log message that shows the "match" result for each application for each packet received as a PacketIn.

**Comment by adibrastegarnia** [comment]
I don't see something unusual in the log:

DEBU[0582] SENDING: all end-points                       header_length=8
length=138 of_message=TypePacketIn of_transaction=0 of_version=4
DEBU[0582] match                                         dl_type=0x8942
DEBU[0582] packet in
context="[0x0000000000000001, 0x0002]"
openflow=040a008a00000000ffffffff00600100000100007a585b6f0001000c8000000400000002000000000000
packet=ffffffffffff02eb9f67c94289420207040000000001920405020000000106020078fe12a42305014f4e4f5320446973636f76657279fe17a42305026f663a30303030303030303030303030313932080d7370696e653430322d657468310000
DEBU[0582] Checking                                      connection="(
http://127.0.0.1:8000/packet, 5)" match=false
DEBU[0582] Checking                                      connection="(
http://127.0.0.1:8000/packet, 0)" match=false
DEBU[0582] SENDING: SDN controller                       length=400
of_message=TypeMultipartReply of_transaction=26485 of_version=4
DEBU[0582] SENDING: SDN controller                       length=352
of_message=TypeMultipartReply of_transaction=79 of_version=4
DEBU[0582] SENDING: SDN controller                       length=6112
of_message=TypeMultipartReply of_transaction=26494 of_version=4
DEBU[0582] SENDING: SDN controller                       length=728
of_message=TypeMultipartReply of_transaction=26484 of_version=4
DEBU[0582] SENDING: SDN controller                       length=464
of_message=TypeMultipartReply of_transaction=79 of_version=4
DEBU[0582] SENDING: SDN controller                       length=6112
of_message=TypeMultipartReply of_transaction=26492 of_version=4
DEBU[0582] SENDING: all end-points                       header_length=8
length=140 of_message=TypePacketIn of_transaction=0 of_version=4
DEBU[0582] match                                         dl_type=0x0800
DEBU[0582] packet in
context="[0x0000000000000191, 0x0002]"
openflow=040a008c00000000ffffffff0062010000010000f3d4623c0001000c8000000400000002000000000000
packet=000000000001000000000002080045000054ec87400040013a1f0a0000020a0000010800d74b47ab0002d9e6695b00000000cff1070000000000101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f3031323334353637
DEBU[0582] Checking                                      connection="(
http://127.0.0.1:8000/packet, 5)" match=true
DEBU[0582] Checking                                      connection="(
http://127.0.0.1:8000/packet, 0)" match=false
DEBU[0582] SENDING: all end-points                       header_length=8
length=140 of_message=TypePacketIn of_transaction=0 of_version=4
DEBU[0582] match                                         dl_type=0x0800
DEBU[0582] packet in
context="[0x0000000000000001, 0x0001]"
openflow=040a008c00000000ffffffff0062010000010000021b41dc0001000c8000000400000001000000000000
packet=000000000001000000000002080045000054ec87400040013a1f0a0000020a0000010800d74b47ab0002d9e6695b00000000cff1070000000000101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f3031323334353637
DEBU[0582] Checking                                      connection="(
http://127.0.0.1:8000/packet, 6)" match=true
DEBU[0582] Checking                                      connection="(
http://127.0.0.1:8000/packet, 0)" match=false
DEBU[0582] SENDING: SDN controller                       length=8
of_message=TypeBarrierReply of_transaction=391 of_version=4
DEBU[0583] SENDING: SDN controller                       length=8
of_message=TypeBarrierReply of_transaction=393 of_version=4
DEBU[0583] SENDING: all end-points                       header_length=8
length=135 of_message=TypePacketIn of_transaction=0 of_version=4
DEBU[0583] match                                         dl_type=0x88cc
DEBU[0583] packet in
context="[0x0000000000000192, 0x0001]"
openflow=040a008700000000ffffffff005d010000010000f687473b0001000c8000000400000001000000000000
packet=0180c200000e02eb9f67c94288cc0207040000000000010405020000000206020078fe12a42305014f4e4f5320446973636f76657279fe17a42305026f663a30303030303030303030303030303031080a6c656166312d657468320000
DEBU[0583] Checking                                      connection="(
http://127.0.0.1:8000/packet, 7)" match=false
DEBU[0583] Checking                                      connection="(
http://127.0.0.1:8000/packet, 0)" match=false



The match is false for LLDP packet. As I mentioned earlier, the etherType
is a negative number but the library detects it as a LLDP packet. Is it
possible that the packet_in is corrupted somehow? I will do more debugging
to see what is going on and then let you know.

Thanks,
Adib

**Comment by dbainbri-ciena** [comment]
The Ethertype is a uint16. Java does not represent unsigned values, so it is likely storing it as a signed Short. So when you print a value like 0x8942, it will be displayed as a negative value.

Given that the matches are both `false`, i am not sure why the packet would be sent to your application.

**Comment by adibrastegarnia** [comment]
Yes. You are right. I printed the hex value of Ethtype, and it is 0x8942. I
will update you if I find its reason.

**Comment by dbainbri-ciena** [comment]
Is it possible for me to replicate your environment wrt to oftee and your app? I would need the command you are using to start oftee and information about how you are creating the network, i.e., is it mininet?

**Comment by adibrastegarnia** [comment]
Yes.

Please clone this repository:

https://github.com/umbrella-project/umbrella

Then :
cd umbrella
mvn package

Run oftee using this configuration:

API_ON=:8005
LISTEN_ON=6654
PROXY_TO=127.0.0.1:6653
TEE_TO="dl_type=0x800;action=http://127.0.0.1:8000/packet,dl_type=0x806;action=http://127.0.0.1:8000/packet"
TEE_RAW=false


After that:
In a new terminal:
1- Run onos
2- cd /umbrella/mininet_examples
3- sudo python leaf_spine.py

In another terminal:
Run TestPacketInOftee app using the following command:
java -cp target/umbrella-1.0-SNAPSHOT-jar-with-dependencies.jar
apps.TestPacketInOftee 8000


Then ping h2 from h1.


Please let me know if you need more info.

Thanks,
Adib

**Comment by adibrastegarnia** [comment]
You should be able to get an output like this:

type:0x00000800
PACKET IN
type:0xFFFFFFFFFFFF8942
java.lang.ClassCastException: org.onlab.packet.LLDP cannot be cast to
org.onlab.packet.IPv4
        at
apps.TestPacketInOftee$1PacketInEventListener.onEvent(TestPacketInOftee.java:82)
        at
drivers.controller.packetService.PacketInEventMonitor.handle(PacketInEventMonitor.java:111)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
        at
sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
        at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
        at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
        at
sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
        at
sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
        at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)

**Comment by davidkbainbridge** [comment]
I did get the following exception, but the OFTEE config is such that your application should be getting 0x806 packets

```
ACKET IN
type:0x00000806
java.lang.ClassCastException: org.onlab.packet.ARP cannot be cast to org.onlab.packet.IPv4
	at apps.TestPacketInOftee$1PacketInEventListener.onEvent(TestPacketInOftee.java:82)
	at drivers.controller.packetService.PacketInEventMonitor.handle(PacketInEventMonitor.java:111)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by adibrastegarnia** [comment]
It doesn't happen always. Please make sure fwd is activated in onos and try
multiple times.  I will test it on another machine to make sure something
is not wrong with my system.

Thanks,
Adib

**Comment by davidkbainbridge** [comment]
I ran and re-ran everything for about an hour and while I saw exceptions in various places, I never once saw `LLDP` packets (`0x8942`) get to the app. I see the `LLDP` packet in OFTEE, but it is not forwarded to the app.

I saw both `IPv4` (`0x0800`) and `ARP` (`0x0806`) forwarded to the app.

**Comment by adibrastegarnia** [comment]
OK. I am going to ask one of my friends to test it as well. Thanks for
spending time on this issue.

**Comment by adibrastegarnia** [comment]
You can also close this one.
