### ISSUE TITLE
Don't get PACKET_IN when deactivate fwd in ONOS

### ISSUE THREAD

**Issue by adibrastegarnia** [ciena/oftee#5]
Hi, 

I found out when I deactivate reactive forwarding in onos, I don't get any packet_in message in my external application. Would you please also check this issue? 

Thanks,
Adib

**Comment by adibrastegarnia** [comment]
I think this is normal because ARP packets need to be handled first.

**Comment by dbainbri-ciena** [comment]
I will look at this, but this shouldn't be the case unless your applications are using the same SDN controlled network on which your client or "data" traffic is using. In a deployment, the management apps are often on a separate management network from your client or data traffic. This is not always the case, but is a common deployment.

I will update this thread after I complete my test, but my default test has a management network that is separate from the data network. I am at the airport right now, so it might be a little delayed depending on when I can get the test done and when the plane boards.

**Comment by adibrastegarnia** [comment]
I think I figured that out. When we deactivate fwd, arp packets is not handled any more. So we when we set TEE_TO to get IP packets, we don't get anything because ARP packets need to be handled first. I think this problem is resolved.

**Comment by dbainbri-ciena** [comment]
Ok, then I will close this. I just completed my simple test, ONOS with only openflow application installed and it worked. But again, i am using a separate mgmt network.
