### ISSUE TITLE
Packet OUT Recevied but not response, no error

### ISSUE THREAD

**Issue by adibrastegarnia** [ciena/oftee#6]
Hi, 
In my application, I create a packet_out (i.e. arp reply to an arp request) and send out over http. This is my observations:

1- OFTEE receives packet out and extracts dpid without any errors (i.e. OFTEE prints this debug statement: Debug("Packet out request recieved")

2- After that nothing happens. No error, no warning, and no response to the application even error (If I send a wrong dpid, it responds with an error so It looks like there is no problem with http connection). 

I went through OFTEE source codes and If my understanding is correct, OFTEE should print at the end: 
.Debug("Writing packet out to device") 
but it does not happen. 

I would like to know under what circumstances, the above scenario happens? 

These are pieces of my code that create and send packet out: 

ARP arpPacket = (ARP) eth.getPayload();
                            Ip4Address targetIpAddress = Ip4Address
                                    .valueOf(arpPacket.getTargetProtocolAddress());

                            log.info("ARP PACKET\n");
                            OFActionOutput output = myFactory.actions().buildOutput()
                                    .setPort(OFPort.ofInt(packetInEvent.getInPortNum()))
                                    .build();

                            Ethernet ethReply = ARP.buildArpReply(targetIpAddress,
                                    eth.getDestinationMAC(),
                                    eth);

                            OFPacketOut packetOut = myFactory.buildPacketOut()
                                    .setData(ethReply.serialize())
                                    .setBufferId(OFBufferId.NO_BUFFER)
                                    .setInPort(OFPort.ANY)
                                    .setActions(Collections.singletonList((OFAction) output))
                                    .build();

---------------------------------------

URL url = null;
                try {
                    url = new URL("http://127.0.0.1:8005/oftee/" +  String.format("0x%016X", dpid));
                } catch (MalformedURLException e) {
                    e.printStackTrace();
                }

                HttpURLConnection con = null;
                con = (HttpURLConnection) url.openConnection();

                con.setDoOutput(true);
                con.setDoInput(true);
                con.setRequestMethod("POST");
                con.setRequestProperty( "Content-Type", "application/octet-stream" );

                OutputStream os = con.getOutputStream();
                ByteBuf packetOutBuffer = Unpooled.buffer();
                ofPacketOut.writeTo(packetOutBuffer);

                //
                //log.info(packetOutBuffer.array().length);

                os.write(packetOutBuffer.array());

                int responseCode = con.getResponseCode();
                log.info("POST Response Code :: " + responseCode + "\n");

**Comment by davidkbainbridge** [comment]
I ran some tests and all is working as expected. Are you running the latest code? Also, if you could send me a complete running example in Java I will try that. I wrote my tests in Go, but don't know all the dependencies, etc you are using in Java. So if you have a small, complete example (i.e. build and send packet) in Java I will try that.

There really doesn't seem to be any reason that you aren't seeing the `Writing...` log message, so please post your logs. The only way I think that is even possible is if somehow the internal channel that the packet out is sent is not working, but for all my examples and tests I have not seen this as the case.

**Comment by adibrastegarnia** [comment]
David,
I will get back to you soon. We are doing some tests on a  remote server
and it looks like we are getting packet out messages (I am waiting to be
confirmed with one my friends as well). I think something is wrong with my
computer. We are writing a reactive fwd app so I will provide you a fully
functional example in java soon.

Thanks,
Adib

**Comment by dbainbri-ciena** [comment]
just pushed some changes that will do minimal validation on packet out requests as well as better logging if oftee rejects a packet out request. the validations include:

- packet must be a minimum len (ofpacket header)
- message must be of type packet out
- byte len specified in OF header must match actual len of data in the request

**Comment by adibrastegarnia** [comment]
Thanks David. Sorry for my late response. We were working on our code to see what is wrong. We found out the size of packet out is wrong and that is the reason the packet gets rejected. I will push the final version of reactive forwarding in our repository soon.

**Comment by davidkbainbridge** [comment]
No worries. Can this issue be closed now?

**Comment by adibrastegarnia** [comment]
Yes.
